name: language-elm
version: '0.2.0.0'
synopsis: Generate elm code
description: Generate elm code from an ast
category: Web
author: Elias Lawson-Fox
maintainer: me@eliaslfox.com
copyright: 2017 Elias Lawson-Fox
license: BSD3
github: eliaslfox/language-elm
extra-source-files:
- README.md
ghc-options:
- -Wall
when:
- condition: impl(ghc >= 8.0)
  ghc-options:
   - -Wwarn=unused-imports
dependencies:
- pretty
- mtl
- protolude
- base >= 4.8 && < 4.13
- semigroups
library:
  source-dirs: src
  exposed-modules:
  - Elm
  - Elm.Declaration
  - Elm.Expression 
  - Elm.Import
  - Elm.Program
  - Elm.Type
  - Elm.Classes
  - Elm.GenError
  dependencies:
  - MissingH
tests:
  language-elm-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-elm
    - hspec
data-files:
- test/program1.elm
- test/spec/*
